# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r app/requirements.txt

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Run __init__.py when the container launches
CMD ["python", "app/__init__.py"]
